LICENSE, PIPREADME.md, README.md, setup.py
=> Release documentation

PIPREADME.md, README.md, instructions/run_integration_text.sh, intelli/controller/remote_vision_model.py, intelli/flow/agents/agent.py, intelli/flow/flow.py, intelli/flow/tasks/task.py, intelli/flow/types.py, intelli/function/chatbot.py, intelli/model/input/image_input.py, intelli/model/input/vision_input.py, intelli/test/integration/test_flow_map.py, intelli/test/integration/test_flow_sequence.py, intelli/test/integration/test_geminiai_wrapper.py, intelli/test/integration/test_remote_vision_model.py, intelli/wrappers/geminiai_wrapper.py, requirements.txt, setup.py
- create unified vision controller.
- update the flow to support vision.
=> 3 create unified vision controller

.gitignore, instructions/run_integration_text.sh, instructions/useful_comands.sh, intelli/controller/remote_speech_model.py, intelli/function/chatbot.py, intelli/model/input/text_speech_input.py, intelli/test/integration/test_googleai_wrapper.py, intelli/test/integration/test_openai_wrapper.py, intelli/test/integration/test_remote_speech_model.py, intelli/wrappers/googleai_wrapper.py, setup.py
Prepare a new release version with following fixes:
- Fix the semantic search parser.
- Add remoate speech controller, a common function to generate audio files using openai or google provider.
=> Prepare release 0.0.9

PIPREADME.md, setup.py
=> update read me and the version

intelli/controller/remote_embed_model.py, intelli/controller/remote_image_model.py, intelli/controller/remote_speech_model.py, intelli/controller/remote_vision_model.py, intelli/flow/agents/agent.py, intelli/flow/flow.py, intelli/flow/tasks/task.py, intelli/flow/template/basic_template.py, intelli/function/chatbot.py, intelli/model/input/chatbot_input.py, intelli/model/input/image_input.py, intelli/model/input/text_speech_input.py, intelli/test/integration/test_flow_icons.py, intelli/utils/conn_helper.py, intelli/utils/proxy_helper.py, intelli/utils/system_helper.py, intelli/wrappers/cohereai_wrapper.py, intelli/wrappers/geminiai_wrapper.py, intelli/wrappers/googleai_wrapper.py, intelli/wrappers/intellicloud_wrapper.py, intelli/wrappers/mistralai_wrapper.py, intelli/wrappers/openai_wrapper.py, intelli/wrappers/stability_wrapper.py, requirements.txt, setup.py
changes:
- update the code format.
- fix bugs.
- adjust the graph module version.
- improve the agent parameter sending.
- add extra flow test case.
=> Testing and formatting

intelli/controller/remote_embed_model.py, intelli/function/chatbot.py, intelli/model/input/chatbot_input.py, intelli/test/integration/test_remote_embed_model.py, setup.py
Prepare the release and bug fixes.
=> Release0.2.2

PIPREADME.md, intelli/flow/agents/agent.py, intelli/flow/agents/kagent.py, intelli/flow/tasks/task.py, setup.py
Update the agent to receive (optional) custom model parameters from the task.
=> Custom params

PIPREADME.md, setup.py
Add the latest changes to the release documentation.
=> update the docs

intelli/flow/agents/kagent.py, intelli/flow/flow.py, intelli/test/integration/test_flow_map.py, setup.py
Update the default agent length and the flow error handeling.
=> Increase default len

intelli/flow/__init__.py, intelli/flow/flow.py, setup.py
Improve the imports and flow error handling.
=> Gemeral improvements

intelli/flow/agents/kagent.py, intelli/function/chatbot.py, intelli/model/input/chatbot_input.py, intelli/test/integration/test_chatbot.py, intelli/wrappers/keras_wrapper.py, setup.py
Create Keras wrapper and update the agent to use it.
Update the chatbot to use the offline model loader.
=> Organize offline model loader

intelli/utils/system_helper.py, setup.py
Reduce the RAG system message text.
=> reduce the RAG system message and publish

intelli/test/integration/test_keras_whisper.py, intelli/utils/whisper_helper.py, intelli/wrappers/keras_wrapper.py, setup.py
Add offline whisper model with extended capabilities such as smart audio slicing and initial prompting.
=> 83 add whisper model

intelli/test/integration/test_keras_whisper.py, intelli/utils/whisper_helper.py, intelli/wrappers/keras_wrapper.py, setup.py
=> 83 improve whisper model

intelli/config.py, intelli/controller/remote_embed_model.py, intelli/function/chatbot.py, intelli/model/input/chatbot_input.py, intelli/model/input/embed_input.py, intelli/test/integration/test_chatbot_nvidia.py, intelli/test/integration/test_nvidia_wrapper.py, intelli/test/integration/test_remote_embed_model_nvidia.py, intelli/wrappers/nvidia_wrapper.py
**Changes**:
- Integration of a new NvidiaWrapper.
- Updates to the chatbot and chatbot input classes to support NVIDIA models (DeepSeek and Llama 3.3).
- Updates to the remote embedding controller and embedding input to include NVIDIA embeddings.
- New test files for the NVIDIA wrapper.
=> Add Nvidia models

PIPREADME.md, README.md, intelli/function/chatbot.py, setup.py
update the version and description with more details about Nvidia models.
=> add latest updates

PIPREADME.md, setup.py
Update pip doc with latest features.
=> Add latest features

PIPREADME.md, intelli/function/chatbot.py, intelli/test/integration/test_nvidia_wrapper_nim.py, intelli/wrappers/nvidia_wrapper.py, setup.py
Add support for localhost LLM.
=> 90 support nvidia nim

PIPREADME.md, README.md, instructions/run_integration_text.sh, intelli/function/chatbot.py, intelli/model/input/chatbot_input.py, intelli/test/integration/test_chatbot_cpp.py, intelli/test/integration/test_llama_cpp_extend_wrapper.py, intelli/test/integration/test_llama_cpp_wrapper.py, intelli/wrappers/llama_cpp_wrapper.py, setup.py
Add support for Llama CPP and GGUF models.
=> 92 integrate llamacpp

intelli/controller/remote_embed_model.py, intelli/model/input/embed_input.py, intelli/test/integration/test_remote_embed_model.py, intelli/test/integration/test_vllm_wrapper.py, intelli/wrappers/vllm_wrapper.py
Add vllm to remote embedding function.
=> Add remote embedding integration

intelli/controller/remote_recognition_model.py, intelli/model/input/text_recognition_input.py, intelli/test/integration/test_remote_recognition_model.py, intelli/wrappers/openai_wrapper.py
Add orchestration function for recognition and related test cases.
=> Add speech recognition function

intelli/config.py, intelli/controller/remote_recognition_model.py, intelli/controller/remote_speech_model.py, intelli/controller/remote_vision_model.py, intelli/model/input/text_recognition_input.py, intelli/model/input/text_speech_input.py, intelli/model/input/vision_input.py, intelli/test/integration/test_elevenlabs_wrapper.py, intelli/test/integration/test_geminiai_wrapper.py, intelli/test/integration/test_googleai_wrapper.py, intelli/test/integration/test_remote_recognition_model.py, intelli/test/integration/test_remote_speech_model.py, intelli/test/integration/test_remote_vision_model.py, intelli/wrappers/elevenlabs_wrapper.py, intelli/wrappers/geminiai_wrapper.py, intelli/wrappers/googleai_wrapper.py
**Changes**:
1. Improve google models integration.
2. Update gemini integration to latest models.
3. Add eleven labs integration.
4. Expand capabilities of remote speech and recognition.
=> 103 improve the wrappers

intelli/controller/remote_recognition_model.py, intelli/flow/agents/agent.py, intelli/flow/agents/handlers.py, intelli/flow/agents/kagent.py, intelli/flow/flow.py, intelli/flow/sequence_flow.py, intelli/flow/tasks/task.py, intelli/flow/types.py, intelli/flow/utils/flow_helper.py, intelli/model/input/text_recognition_input.py, intelli/test/integration/test_flow_map.py, intelli/test/integration/test_flow_master.py, intelli/test/integration/test_remote_embed_model.py, intelli/test/integration/test_remote_speech_model.py, setup.py
Refactored agent architecture with specialized handlers for text, vision, speech, and image models for improved modularity.
=> 105 improve the flow

PIPREADME.md, intelli/flow/__init__.py, setup.py
Improve the inner classes import using `init` file.
=> Update the version

intelli/flow/flow.py, setup.py
Add parameter to control legend visibility.
=> add extra parameter to generate_graph_img

intelli/flow/flow.py, intelli/model/input/chatbot_input.py, setup.py
**Changes**:
Improve the data integration between tasks.
Add optional sleep time between tasks.
=> Minor enhacement medpaper

intelli/flow/template/basic_template.py, setup.py
=> Update the template

instructions/run_integration_text.sh, intelli/flow/__init__.py, intelli/flow/flow.py, intelli/flow/sequence_flow.py, intelli/flow/store/basememory.py, intelli/flow/store/dbmemory.py, intelli/flow/store/memory.py, intelli/flow/tasks/task.py, intelli/flow/template/basic_template.py, intelli/test/integration/test_flow_memory.py, intelli/test/integration/test_flow_with_dbmemory.py, intelli/test/integration/test_memory.py, intelli/utils/conn_helper.py, setup.py
Improve the agents collaboration and add memory feature
=> 116 improve multi agent collaboration

instructions/run_integration_text.sh, intelli/flow/__init__.py, intelli/flow/utils/__init__.py, intelli/flow/utils/mcp_utils.py, sample/mcp/http_math_flow_client.py, sample/mcp/http_mcp_calculator_server.py, sample/mcp/math_flow_client.py, sample/mcp/mcp_math_server.py, setup.py
Improve the client and server using utils to reduce the code.
=> Adjust the MCP to use utils for easy integration

instructions/run_integration_text.sh, intelli/flow/flow.py, intelli/test/integration/test_mcp_openai_flow.py
Optimize Flow Graph Legend Generation
Changes:
- Modified the generate_graph_img function to only display legend entries.
- Update the MCP test cases to generate the graph image.
=> Optimize Flow Graph Legend

intelli/flow/flow.py, sample/mcp/http_math_flow_client.py
Add export graph function to the samples.
=> Add graph to the sample and adjust the node label

README.md, instructions/run_integration_text.sh
Second merge - Adjust the install in readme.
=> 129 add a pandas mcp connector

intelli/config.py, intelli/controller/remote_image_model.py, intelli/model/input/image_input.py, intelli/wrappers/geminiai_wrapper.py
=> Update Gemini Flow to accept model name

instructions/how to docs/DYNAMIC_TOOL.md
Update the dynamic tool connector documentation.
Changes:
- Add a section for the description of the parameters.
=> Update tools doc

instructions/how to docs/DYNAMIC_TOOL.md, intelli/flow/flow.py
Update the Dynamic Tool Routing docs
=> Improve the mcp integration
